### PR TITLE
With Component.Import check for public constructor

### PR DESCRIPTION
**Pull request by rbygrave**
So the DI class to wire the imported component will be in the same package as the component unless it has a public constructor, and then it can be put into a
di subpackage.

### CODE REVIEW

**Comment by SentryMan** [comment]
does this mean we can remove the new attribute I added to `@Import`?

**Comment by rbygrave** [comment]
> does this mean we can remove the new attribute I added to @Import?

Well yeah I think we could actually.

**Comment by SentryMan** [comment]
let's toss it then

**Comment by rbygrave** [comment]
Ok yeah, makes sense cause we probably don't expect people to use it so yup - ok, I'll do that.

**Review by SentryMan — APPROVED** [review]
LGTM

**Pull request merged**
