### PR TITLE
Add annotation for module-path `InjectPlugin` auto-detection

### LINKED ISSUE #724: Module-Path Detection doesn't work for test compile
As the title says, it seems during test compilation `getAllModuleElements` doesn't work.

To resolve, we can try to write an `avaje-module-dependencies.csv` in the compile stage so it can be picked up during the test-compile step.

### PR DESCRIPTION
**Pull request by SentryMan**
- adds a `@PluginProvides` annotation that the processor can autodetect via `getAllModuleElements` (not sure I like the name though, feel free to change it if you got a better one)
- writes plugin/module text files for reuse during test compilation 

resolves #724

### CODE REVIEW

**Comment by SentryMan** [comment]
@rbygrave yeah I'm good with this: (unless you have a better name for the annotation)

**Comment by rbygrave** [comment]
> adds a @PluginProvides annotation 

Why do you want to add this? Why do you think we need this?

**Comment by SentryMan** [comment]
> Why do you want to add this? Why do you think we need this?

With this, I can create internal plugin libraries that will be auto-detected by avaje inject without needing a maven/gradle plugin. I've got a couple of internal ones that this would be convenient to have. It is the natural extension of https://github.com/avaje/avaje-inject/issues/716.

**Comment by SentryMan** [comment]
Currently, we need to use the `inject-maven-plugin` if:

- the application is using the maven compiler plugin `annotationProcessorPaths`
- The application has a module-info

This PR makes it so that the `inject-maven-plugin` is only required if:

- the application doesn't have a module-info _**and**_ the application is using the maven compiler plugin `annotationProcessorPaths`

As I like to make use of JPMS, this PR is very convenient for me

**Comment by rbygrave** [comment]
> I can create internal plugin libraries 

Like what? Why are you creating plugins rather than using "normal dependencies"?  That is, I'm not really expecting many people to create plugins at all.


> without needing a maven/gradle plugin

People just need to register a service loader right, so they don't need a maven/gradle plugin for that? I don't get it?


> natural extension of https://github.com/avaje/avaje-inject/issues/716

I don't see that no, in that I'm really expecting people to use "normal dependencies" and only very few expert users will create plugins. So no I don't see that point.

**Comment by SentryMan** [comment]
> Like what? Why are you creating plugins rather than using "normal dependencies"? 

A plugin I have is for one of our encryption libraries. It only exposes a single class so a plugin that provides a single instance is a natural choice. I have a similar structure to the jsonb/validator plugins to configure it.

> That is, I'm not really expecting many people to create plugins at all.

Yeah but for the people who do, this would be pretty convenient for their consumers.

**Comment by SentryMan** [comment]
> People just need to register a service loader right, so they don't need a maven/gradle plugin for that? I don't get it?

Ah wait I think I might see the disconnect. I'm talking about the consumer of custom `InjectPlugin`s when I say they need a maven plugin.

Suppose I create a plugin `EncryptPlugin` and register it with the `ServiceLoader`

```java
public class EncryptPlugin implements InjectPlugin {

  @Override
  public Class<?>[] provides() {

    return new Class<?>[] {Encryptor.class};
  }

  @Override
  public void apply(BeanScopeBuilder builder) {
   Encryptor e = ...
    builder.beans(e);
  }
}
```

When someone pulls in the maven dependency for this library and tries to use it like this:
```java
@Singleton
public class WireOther {
  Encryptor e;

  public WireOther(Encryptor e) {
    this.e = e;
  }
}
```

Compilation will fail if any of these are true

- the application is using the maven compiler plugin `annotationProcessorPaths`
- The application has a module-info

the reason is that the inject generator cannot read what classes the `EncryptPlugin` provides without help

**Review by rob-bygrave — APPROVED** [review]

**Comment by SentryMan** [comment]
@rbygrave perchance can you deploy an RC when you find the time?

**Comment by rbygrave** [comment]
Hmmm. https://s01.oss.sonatype.org is currently returning status code 503 ... but yeah will do it shortly hopefully.

**Pull request merged**
