### PR TITLE
Use Avaje Prisms instead of referencing annotations directly

### PR DESCRIPTION
**Pull request by SentryMan**
For auto requires, you'll need to use the inject maven plugin though.

- Use Avaje(Hickory) prisms to access annotation information 
- Only service load modules/plugins if inject is on the classpath
- replace that one Stack with a Deque

takes care of #276

### CODE REVIEW

**Comment by rbygrave** [comment]
Just to say I wouldn't invest too much time into this as I'm likely to go the path of using TypeElement / TypeMirror / AnnotationMirror (as I mentioned earlier).

**Comment by SentryMan** [comment]
I mean I got it working, and it works when I modularize my javalin project. But it is what it is I suppose.

**Comment by SentryMan** [comment]
> Just to say I wouldn't invest too much time into this as I'm likely to go the path of using TypeElement / TypeMirror / AnnotationMirror (as I mentioned earlier).

Sure you won't change your mind? hickory seems pretty rad and easy to use compared to AnnotationMirrors.

**Comment by rbygrave** [comment]
Maybe. I'll put up a branch and we can compare ... noting that in the back of my mind there is:

- This library is expected to live for a long time / many years longevity / think 15 years 
- I need to 'own' it _including dependencies_ like hickory and I can't assume people will help over the maintenance lifetime

**Comment by SentryMan** [comment]
> think 15 years
hmm, I would have thought that number would be higher. 

> I can't assume people will help over the maintenance lifetime
I like to stay optimistic about these sorts of things. One could even argue that having hickory makes the code easier to parse when compared to Annotation Mirrors and so would make it more likely for people to contribute.

In any case, if it breaks something in the future, my pride won't allow me to leave it broken if I was the one who caused it. I'd be the first to remove it.

**Comment by agentgt** [comment]
@rbygrave Hickory is highly stable but just not supported. It is a very simple project and I was planning on forking it and releasing an updated version to maven central.

It is important to understand that Hickory is never a true dependency. It is a zero dep code generator. The annotations it use are retention = SOURCE. The code it produces has zero references to anything hickory. In fact it inspired me to make my own annotation library produce zero dep code as an option: https://jstach.io/jstachio/#maven_zerodep

MapStruct has gemtools which is a more update to date fork but sadly unlike Hickory it is not zero dep: https://github.com/mapstruct/tools-gem/issues/11

If @SentryMan and I did not use it the code change would not have happened in a couple of hours like we did yesterday.

Of course avaje instead of me could host a fork of hickory and then you would guarantee its future for these libraries. I'm planning to do it for jstachio at some point this month.

**Comment by SentryMan** [comment]
Looks like prisms are back on the menu boys

**Comment by rbygrave** [comment]
This was merged in via a squashed commit - https://github.com/avaje/avaje-inject/commit/064d8be4c47daeb51c4bbc5c03e1aed1f07e5403

**Comment by rbygrave** [comment]
Closing as merged via the squashed commit - https://github.com/avaje/avaje-inject/commit/064d8be4c47daeb51c4bbc5c03e1aed1f07e5403 , these changes will be in 8.12

**Pull request closed without merging**
