### PR TITLE
Add Closeable Option to Factory Beans

### PR DESCRIPTION
**Pull request by SentryMan**
I prefer doing things at compile time if possible, so I'm still not 100% sold on this. Related to #290

### CODE REVIEW

**Comment by rbygrave** [comment]
As an alternative to this ... add an explicit attribute to `@Bean` like `@Bean(autoClosable=true)` and when this is set to true then generate the extra check 

```java
@Factory 
MyFactory {

  @Bean(autoCloseable=true) // if the instance is AutoClosable register it with PreDestory
  DataSource datasource() {
   ...
  }

}

```

So instead of the usual:
```java
    if (builder.isAddBeanFor(DataSource.class)) {
      var factory = builder.get(MyFactory.class);
      var bean = factory.data();
      builder.register(bean);
    }
```


Generate code to that sends the registered bean to a `addPreDestroy($bean)` method (that takes Object and does the instance of check)
```java
    if (builder.isAddBeanFor(DataSource.class)) {
      var factory = builder.get(MyFactory.class);
      var bean = factory.data();
      var $bean = builder.register(bean);
      builder.addPreDestroy($bean);
    }
```

The extra generated code with `@Bean(autoClosable=true)` is the ... 
```java
    
      var $bean = 
      builder.addPreDestroy($bean);
    
```

**Comment by SentryMan** [comment]
ok I can roll with that

**Comment by rbygrave** [comment]
I extended this PR via https://github.com/avaje/avaje-inject/pull/296 ... to move the if block and `instance of AutoCloseable` check into a new `builder.addAutoCloseable()` method.

**Comment by rbygrave** [comment]
Some the changes in this PR are effectively included in https://github.com/avaje/avaje-inject/pull/296 but I squashed the commit when I merged it into master.

We can close this with the changes here being merged into master.

**Pull request closed without merging**
