### PR TITLE
Show failing with compiler plugin

### PR DESCRIPTION
**Pull request by SentryMan**
#272

### CODE REVIEW

**Comment by rbygrave** [comment]
FYI: blackbox-aspect is missing META-INF/services/io.avaje.inject.spi.Module ...

**Comment by SentryMan** [comment]
it's there in the blackbox-aspect jar

**Comment by rbygrave** [comment]
> it's there in the blackbox-aspect jar created by jar plugin

Ah yeah, I forgot that the annotation processor automatically generates that file for us.

WRT this issue, a "thing that works that we don't want to do" is to add the `blackbox-aspect` into the `<annotationProcessorPaths>` `<path>` like:
```
          <annotationProcessorPaths>
            <path>
              <groupId>io.avaje</groupId>
              <artifactId>avaje-inject-generator</artifactId>
              <version>${project.version}</version>
            </path>
            <path>
              <groupId>io.avaje</groupId>
              <artifactId>blackbox-aspect</artifactId>
              <version>${project.version}</version>
            </path>
          </annotationProcessorPaths>
```
... which is a strong indication that it's a classpath / module-path issue.

This makes me ponder that the path going forward might be to replace the service loading with ... find the module classes, find the TypeElement (of the external modules) ... find their methods ... read the `@DependencyMeta` from the methods.  (This is what the AP already does in order to support partial compiles, ... we approximately extend that to read the  `@DependencyMeta` from all the external inject modules as well.

So time for lunch and will ponder that ...

**Comment by SentryMan** [comment]
It seems the classpath just isn't there during the mvn compiler plugin. I tried using Class.forName to try and manually get the module but it didn't work.

**Comment by rbygrave** [comment]
> It seems the classpath just isn't there during the mvn compiler plugin

Yes I agree.  

This is suggesting to me that ServiceLoader just isn't going to work for us here ... need to instead look at reading the `@DependencyMeta` via the TypeElements etc.  Also means the ServiceLoader for Plugin also isn't going to work.

**Comment by SentryMan** [comment]
It doesn't look like TypeElements work when the classpath isn't there. We may have to do something wacky with the class loading. Or else we can say it's our loss and accept that this will only work when we do it as a provided dependency.

**Comment by SentryMan** [comment]
jsonb plugin works though, because jsonb is added to the cp by the generator AP

**Comment by SentryMan** [comment]
oh wait, this also means that jsonb imports won't work on dependencies if using the mvn compiler plugin.

**Comment by SentryMan** [comment]
or alternatively, I'm actually panicking for no reason, because type elements do in fact work without the cp. Jsonb is fine. I'm still having trouble loading the generated module classes with type elements though

**Comment by rbygrave** [comment]
I have a plan of creating a maven plug in that prior to the compile phase
reads the classpath and writes a file with the class names of the other
modules in the classpath. Then ExternalProvides can read that file.

**Comment by SentryMan** [comment]
> I have a plan of creating a maven plug in that prior to the compile phase reads the classpath and writes a file with the class names of the other modules in the classpath. Then ExternalProvides can read that file.

ok

**Pull request closed without merging**
