### PR TITLE
Rename `isAddBeanFor` to `isBeanAbsent`

### PR DESCRIPTION
**Pull request by SentryMan**
I feel this rolls off the tongue a little better.

- deprecated the old methods for removal in 11
- change generation to use the new name

### CODE REVIEW

**Comment by rbygrave** [comment]
Hmmm, `isBeanAbsent` is kind of ok but also kind of misleading [when parentOverride is true].

**Comment by SentryMan** [comment]
how about `canRegister`?

**Comment by SentryMan** [comment]
10.5 is looking pretty stacked, this can probably be the last feature to add

**Comment by rbygrave** [comment]
I don't think `canRegister()` is an improvement. I'd say `isBeanAbsent` was better than `canRegister`. I'm just not sure about `isBeanAbsent` yet.

**Pull request merged**
