### PR TITLE
Use CodeGen for AOP Fallback

### PR DESCRIPTION
**Pull request by SentryMan**
The current way of using fallback methods is pretty obtuse, so this adds

- Adds a new annotation to mark a method as a fallback for AOP.
- will generate code to register a fallback method to an invocation
- Adds new method to `Invocation` to invoke a registered fallback method
- also will use method references in generated proxies if possible

Given stuff like this:
```java

  @MyRetry
  public String retry2(String param0, int param1) {
    retryWithFallbackCounter++;
    throw new IllegalArgumentException("Retry2Fail[" + param0 + "," + param1 + "]");
  }

  @AOPFallback("retry2")
  public String fallbackRetry2(String param0, int param1, Throwable e) {
    return "fallbackRetry2-" + param0 + ":" + param1 + ":" + e.getMessage();
  }
```
this will get generated
```java
  @Override
  public java.lang.String retry2(String param0, int param1) {
    var call = new Invocation.Call<>(() -> super.retry2(param0, param1))
      .with(this, retry20, param0, param1)
      .fallback(ex -> fallbackRetry2(param0, param1, ex));
    try {
      retry20MyRetry.invoke(call);
      return call.finalResult();
    } catch (RuntimeException ex) {
      ex.addSuppressed(new InvocationException("retry2 proxy threw exception"));
      throw ex;
    } catch (Throwable t) {
      throw new InvocationException("retry2 proxy threw exception", t);
    }
  }

### CODE REVIEW

**Comment by SentryMan** [comment]
@rbygrave waiting for your thoughts before I start in on the method signature validation

**Comment by rbygrave** [comment]
> waiting for your thoughts before I start on the method signature validation

So yes I'm happy so far.

> start on the method signature validation

I'm not sure specifically what you mean there.  Maybe the new methods on Invocation?

**Comment by SentryMan** [comment]
yeah, I'm good with this

**Comment by SentryMan** [comment]
Feel free to change the names of method/class names

**Comment by rbygrave** [comment]
> change the names of method/class names

For myself, I feel the ideal name for `@AOPFallback` would be `@Fallback` but we can't do that at the moment as that is the name of the deprecated interface that will be removed at some stage.

This is a really nice improvement for doing fallback methods - way better than the existing approach.

**Pull request merged**
